import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const rootDir = process.cwd();
const pagesDir = path.join(rootDir, 'docs', 'modules', 'ROOT', 'pages');
const imagesDir = path.join(rootDir, 'docs', 'modules', 'ROOT', 'assets', 'images');
const wikiDir = path.join(rootDir, 'build', 'wiki');

const wikiNameMap = {
  'index.adoc': 'Home.adoc',
  'overview.adoc': 'Overview.adoc',
  'gameplay.adoc': 'Gameplay.adoc',
  'scoring.adoc': 'Scoring.adoc',
  'controls.adoc': 'Controls.adoc',
  'strategy.adoc': 'Strategy.adoc',
  'levels.adoc': 'Levels.adoc',
  'powerups.adoc': 'Powerups.adoc',
  'faq.adoc': 'FAQ.adoc',
  'release-notes.adoc': 'Release-Notes.adoc'
};

const sourceNotice = '// GENERATED FILE: Do not edit this file directly. Update Antora source under docs/ and re-run wiki generation.\n\n';

function fileNameToWikiPageName(sourceFileName) {
  const mapped = wikiNameMap[sourceFileName];
  if (mapped) return mapped;

  const stem = sourceFileName.replace(/\.adoc$/i, '');
  const titleCase = stem
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('-');

  return `${titleCase}.adoc`;
}

function sourceFileToWikiPage(sourceFileName) {
  return fileNameToWikiPageName(sourceFileName).replace(/\.adoc$/i, '');
}

function convertAntoraXrefs(content) {
  // Converts Antora xref syntax such as:
  // xref:overview.adoc[Overview]
  // xref:release-notes.adoc[]
  // into GitHub Wiki-friendly links:
  // link:Overview[Overview]
  // link:Release-Notes[Release Notes]
  return content.replace(/xref:([\w.-]+\.adoc)\[([^\]]*)\]/g, (_match, targetFile, text) => {
    const targetPage = sourceFileToWikiPage(targetFile);
    const fallbackText = targetPage.replace(/-/g, ' ');
    const label = text && text.trim() ? text.trim() : fallbackText;
    return `link:${targetPage}[${label}]`;
  });
}

function wikiTitleFromOutputFile(outputFileName) {
  return outputFileName
    .replace(/\.adoc$/i, '')
    .replace(/^Home$/i, 'Home')
    .replace(/-/g, ' ');
}

async function ensureDirectory(pathname) {
  await mkdir(pathname, { recursive: true });
}

async function generateWikiPages() {
  await rm(wikiDir, { recursive: true, force: true });
  await ensureDirectory(wikiDir);

  const pageEntries = await readdir(pagesDir, { withFileTypes: true });
  const sourcePages = pageEntries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.adoc'))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  if (sourcePages.length === 0) {
    throw new Error(`No AsciiDoc pages found in ${pagesDir}`);
  }

  for (const sourceFile of sourcePages) {
    const sourcePath = path.join(pagesDir, sourceFile);
    const outputName = fileNameToWikiPageName(sourceFile);
    const outputPath = path.join(wikiDir, outputName);

    const raw = await readFile(sourcePath, 'utf8');
    const converted = convertAntoraXrefs(raw);
    await writeFile(outputPath, `${sourceNotice}${converted}`, 'utf8');
  }

  const sidebarItems = sourcePages.map((sourceFile) => {
    const outputName = fileNameToWikiPageName(sourceFile);
    const page = outputName.replace(/\.adoc$/i, '');
    const title = wikiTitleFromOutputFile(outputName);
    return `* link:${page}[${title}]`;
  });

  const sidebarContent = `${sourceNotice}= Navigation\n\n${sidebarItems.join('\n')}\n`;
  await writeFile(path.join(wikiDir, '_Sidebar.adoc'), sidebarContent, 'utf8');

  try {
    await cp(imagesDir, path.join(wikiDir, 'images'), { recursive: true, force: true });
  } catch (error) {
    if (error && error.code !== 'ENOENT') {
      throw error;
    }
  }
}

async function main() {
  try {
    await generateWikiPages();
    console.log(`Wiki pages generated in ${wikiDir}`);
  } catch (error) {
    console.error('Failed to generate wiki pages.');
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}

main();
