import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const rootDir = process.cwd();
const modulesDir = path.join(rootDir, 'docs', 'modules');
const wikiDir = path.join(rootDir, 'build', 'wiki');

// GitHub Wiki only indexes AsciiDoc pages saved with the .asciidoc extension;
// files ending in .adoc are stored in the wiki Git repo but never rendered as
// pages. Source files under docs/ keep .adoc — only the wiki output differs.
const wikiExtension = '.asciidoc';

function stripWikiExtension(outputFileName) {
  return outputFileName.replace(/\.asciidoc$/i, '');
}

// Only ROOT pages whose wiki name cannot be derived by simple title-casing need
// an explicit mapping. Every other page falls back to fileNameToWikiPageName.
const wikiNameMap = {
  'index.adoc': `Home${wikiExtension}`,
  'faq.adoc': `FAQ${wikiExtension}`,
  'kpop.adoc': `K-Pop${wikiExtension}`,
  'privacy.adoc': `Privacy-Policy${wikiExtension}`
};

const sourceNotice = '// GENERATED FILE: Do not edit this file directly. Update Antora source under docs/ and re-run wiki generation.\n\n';

// Segments that title-casing would otherwise mangle, e.g. "ios" -> "Ios".
const specialSegments = {
  ios: 'iOS',
  faq: 'FAQ'
};

function titleCase(stem) {
  return stem
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => {
      const special = specialSegments[part.toLowerCase()];
      if (special) return special;
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    })
    .join('-');
}

function fileNameToWikiPageName(sourceFileName) {
  const mapped = wikiNameMap[sourceFileName];
  if (mapped) return mapped;

  return `${titleCase(sourceFileName.replace(/\.adoc$/i, ''))}${wikiExtension}`;
}

// GitHub Wiki has a single flat page namespace, so pages outside ROOT are
// prefixed with their module name to keep names unique: platforms/android.adoc
// becomes Platforms-Android, and a module's index.adoc becomes the module's own
// page (platforms/index.adoc -> Platforms).
function wikiFileNameFor(moduleName, sourceFileName) {
  if (moduleName === 'ROOT') {
    return fileNameToWikiPageName(sourceFileName);
  }

  const modulePrefix = titleCase(moduleName);
  if (sourceFileName.toLowerCase() === 'index.adoc') {
    return `${modulePrefix}${wikiExtension}`;
  }

  return `${modulePrefix}-${titleCase(sourceFileName.replace(/\.adoc$/i, ''))}${wikiExtension}`;
}

async function directoryExists(pathname) {
  try {
    return (await stat(pathname)).isDirectory();
  } catch {
    return false;
  }
}

async function listAdocFiles(dir) {
  if (!(await directoryExists(dir))) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.adoc'))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

// ROOT first, then the remaining modules alphabetically, so the sidebar keeps
// the shape it had before other modules existed.
async function listModules() {
  const entries = await readdir(modulesDir, { withFileTypes: true });
  const names = entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
  return names.sort((a, b) => {
    if (a === 'ROOT') return -1;
    if (b === 'ROOT') return 1;
    return a.localeCompare(b);
  });
}

function convertAntoraXrefs(content, currentModule, pageIndex) {
  // Converts Antora xref syntax into GitHub Wiki-friendly links, resolving both
  // same-module refs (xref:overview.adoc[]) and module-qualified ones
  // (xref:ROOT:settings.adoc[Settings]).
  return content.replace(
    /xref:(?:([\w-]+):)?([\w.-]+\.adoc)\[([^\]]*)\]/g,
    (_match, targetModule, targetFile, text) => {
      const moduleName = targetModule || currentModule;
      const targetPage =
        pageIndex.get(`${moduleName}/${targetFile}`) ??
        stripWikiExtension(wikiFileNameFor(moduleName, targetFile));
      const fallbackText = targetPage.replace(/-/g, ' ');
      const label = text && text.trim() ? text.trim() : fallbackText;
      return `link:${targetPage}[${label}]`;
    }
  );
}

// The wiki has no per-module image namespace either, so each module's images
// are copied to images/<module>/ and the macros are rewritten to match.
function rewriteImagePaths(content, moduleName) {
  return content.replace(/image::(?!images\/|https?:)([\w./-]+)\[/g, (_match, target) => {
    return `image::images/${moduleName}/${target}[`;
  });
}

async function expandPartials(content, partialsDir, seen = new Set()) {
  // GitHub Wiki does not resolve AsciiDoc include directives, so Antora
  // `include::partial$<file>[]` references are inlined here. Partials resolve
  // within the module that owns the page. Includes are expanded recursively
  // with a guard against partials that include themselves.
  const includePattern = /^[ \t]*include::partial\$([\w./-]+)\[[^\]]*\][ \t]*$/gm;
  const matches = [...content.matchAll(includePattern)];
  if (matches.length === 0) {
    return content;
  }

  let result = '';
  let cursor = 0;
  for (const match of matches) {
    result += content.slice(cursor, match.index);
    const partialName = match[1];
    if (seen.has(partialName)) {
      throw new Error(`Circular partial include detected: ${partialName}`);
    }
    const partialRaw = await readFile(path.join(partialsDir, partialName), 'utf8');
    const expanded = await expandPartials(partialRaw, partialsDir, new Set([...seen, partialName]));
    result += expanded.trimEnd();
    cursor = match.index + match[0].length;
  }
  result += content.slice(cursor);
  return result;
}

function wikiTitleFromOutputFile(outputFileName) {
  return stripWikiExtension(outputFileName)
    .replace(/^Home$/i, 'Home')
    .replace(/-/g, ' ');
}

async function ensureDirectory(pathname) {
  await mkdir(pathname, { recursive: true });
}

async function collectPages() {
  const modules = await listModules();
  const pages = [];

  for (const moduleName of modules) {
    const pagesDir = path.join(modulesDir, moduleName, 'pages');
    for (const sourceFile of await listAdocFiles(pagesDir)) {
      pages.push({
        moduleName,
        sourceFile,
        sourcePath: path.join(pagesDir, sourceFile),
        partialsDir: path.join(modulesDir, moduleName, 'partials'),
        outputName: wikiFileNameFor(moduleName, sourceFile)
      });
    }
  }

  return pages;
}

const imageExtensions = new Set(['.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp']);

async function copyModuleImages(moduleName) {
  const imagesDir = path.join(modulesDir, moduleName, 'assets', 'images');
  if (!(await directoryExists(imagesDir))) return;
  await cp(imagesDir, path.join(wikiDir, 'images', moduleName), {
    recursive: true,
    force: true,
    // Skip anything that is not an image — the source tree also carries notes
    // on how the screenshots were captured, which the wiki has no use for.
    filter: (source) => {
      const extension = path.extname(source).toLowerCase();
      return extension === '' || imageExtensions.has(extension);
    }
  });
}

async function generateWikiPages() {
  await rm(wikiDir, { recursive: true, force: true });
  await ensureDirectory(wikiDir);

  const pages = await collectPages();
  if (pages.length === 0) {
    throw new Error(`No AsciiDoc pages found under ${modulesDir}`);
  }

  const duplicates = new Set();
  const seenOutputNames = new Set();
  for (const page of pages) {
    if (seenOutputNames.has(page.outputName)) duplicates.add(page.outputName);
    seenOutputNames.add(page.outputName);
  }
  if (duplicates.size > 0) {
    throw new Error(`Wiki page name collision: ${[...duplicates].join(', ')}`);
  }

  const pageIndex = new Map(
    pages.map((page) => [
      `${page.moduleName}/${page.sourceFile}`,
      stripWikiExtension(page.outputName)
    ])
  );

  for (const page of pages) {
    const raw = await readFile(page.sourcePath, 'utf8');
    const inlined = await expandPartials(raw, page.partialsDir);
    const converted = convertAntoraXrefs(inlined, page.moduleName, pageIndex);
    const withImages = rewriteImagePaths(converted, page.moduleName);
    await writeFile(path.join(wikiDir, page.outputName), `${sourceNotice}${withImages}`, 'utf8');
  }

  const sidebarItems = pages.map((page) => {
    const name = stripWikiExtension(page.outputName);
    return `* link:${name}[${wikiTitleFromOutputFile(page.outputName)}]`;
  });

  const sidebarContent = `${sourceNotice}= Navigation\n\n${sidebarItems.join('\n')}\n`;
  await writeFile(path.join(wikiDir, `_Sidebar${wikiExtension}`), sidebarContent, 'utf8');

  for (const moduleName of await listModules()) {
    await copyModuleImages(moduleName);
  }

  return pages.length;
}

async function main() {
  try {
    const pageCount = await generateWikiPages();
    console.log(`Wiki pages generated in ${wikiDir} (${pageCount} pages)`);
  } catch (error) {
    console.error('Failed to generate wiki pages.');
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}

main();
